name: Kindmetrics CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: "*"

jobs:
  check_format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:0.34.0
    steps:
      - uses: actions/checkout@v1
      - name: Install shards
        run: shards install
      - name: Format
        run: crystal tool format --check
  specs:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:0.34.0
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Install postgres
      run: apt-get install postgres-contrib
    - name: Install shards
      run: shards install
    - name: Cache Crystal
      uses: actions/cache@v1
      with:
        path: ~/.cache/crystal
        key: ${{ runner.os }}-crystal
    - name: Run tests
      run: crystal spec
